### ISSUE TITLE
[Bug] Invalid chart NOTES.txt

### ISSUE THREAD

**Issue by oleobal** [Substra/orchestrator#100]
## Description

When installing the orchestrator, the NOTES.txt don't display any relevant information.

## Steps to reproduce

Run:
```
helm upgrade --install \
  orchestrator orchestrator \
  --repo https://substra.github.io/charts \
  --version 7.4.6 \
  --namespace orchestrator \
  --create-namespace \
  --values values/orchestrator.yaml
```

With these values:

<details>
<summary>values.yaml</summary>

```yaml
orchestrator:
  image:
    tag: &orchestrator-tag 0.30.0
  mode: standalone
  logLevel: DEBUG
  logSQL: true

postgresql:
  enabled: true
  primary:
    persistence:
      enabled: true
      size: 50Gi

ingress:
  enabled: true
  hostname: "orchestrator.vbai-pilot.cg.owkin.tech"
  annotations:
    kubernetes.io/ingress.class: nginx


channels: [{"name":"channel-1","organizations":["Bridge2AIMSP","WCMMSP","USFMSP"]}]
```
</details>

## Expected behavior

A message telling me what IP or address the deployment endpoint uses.

## Relevant log output

<details>
<summary>terminal output</summary>

```
NAME: orchestrator
LAST DEPLOYED: Wed Dec  7 10:56:35 2022
NAMESPACE: orchestrator
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
```
(this is the entire output of running `helm install`)
</details>

## Context

* Orchestrator chart version: 7.4.6

## Appendix

This file: https://github.com/Substra/orchestrator/blob/main/charts/orchestrator/templates/NOTES.txt
